class loanpath::params{
	$scm_branch = 'master'
	$scm_path = 'https://github.com/trustarun/lp_war.git'
	$war_file = "vms-dauphine-web.war"
	$project_name = "dauphine"

	#integration profile parameters
	$integration_xml_log_directory_path="logs"
	$integration_servcie_config_locations="/integration/config/integrationServiceConfig.xml"
	$integration_xstreamext_config_loader_class="com.thirdpillar.foundation.webservices.utils.CodifyXstreamExtConfigLoader"
	$integration_log_marshaler_task_data="true"
	$integration_log_unmarshaler_task_data="true"
	$integration_log_transformer_task_data="true"
	$integration_log_transport_task_data="true"
	$integration_log_validator_task_data="false"
	$integration_log_custom_task_data="true"
	$esb_smx_external_url="http://10.1.5.1:8192"
	$esig_register_external_host="http://10.1.5.60:8080"
	$esig_citadel_external_host="http://10.1.5.60:8080"
	$esig_citadel_authentication_user="citadel.client"
	$esig_citadel_authentication_password="tps123"
	$esb_authuser="esbuser"
	$esb_authpassword="password"
	$esig_authuser="amadmin"
	$esig_authpassword="rootroot"


	#wep properties configuration parameters
	$email_host = "10.1.1.214"
	$email_port = "25"
	$email_userName = "tpsmail"
	$email_password = "tpsmail"
	$email_use_external_client = "true"
	$email_default_from_address = "no-reply@thirdpillar.com"
	$webapp_server_scheme = "http"
	$webapp_server_name = "10.1.5.122"
	$webapp_server_port = "80"
	$webapp_server_contextpath = "loanpath-tuscany-web"
	$webapp_server_url = "http:://10.1.5.122:80"
	$webapp_server_baseurl = "http:://10.1.5.122:80/loanpath-tuscany-web"
	$security_authentication_expirePasswordInDays = "90"
	$security_authentication_maxFailedLoginAttempts = "5"
	$application_disbursement_external_url = "http://wltwe02w.ltw-p01.chp.bankofamerica.com/LoanEx/LoanEx.DisbursementTool.Client.Dev.application?Action=SUM&ProductId="
	$webapp_server_portalurl = "http://loanpathoob-portal.thirdpillar.com"
	$noia_trigger_scheduler_expression = "0 0 12 * * ? 2100"
	$ucc_search_order_status_scheduler_expression = "0 0 21 * * ?"
	$print_docs_scheduler_expression = "0 0 21 * * ?"
	$hibernate_ehcache_file = "ehcache-default.xml"
	$document_pdf_encryption_ownerPassword = "password"
	$document_pdf_watermark_text = "E-Copy"
	$implementation_practice_enabled = "true"
	$default_homeUrl = "/search/request/main/results.seam"
}
